apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kiamol-4
spec:
  selector:
    matchLabels:
      app: hello-kiamol-4
  template:
    metadata:  # Add metadata section for the template
      labels:
        app: hello-kiamol-4
    spec:  # Correctly spelled 'spec'
      containers:
      - name: web
        image: kiamol/ch02-hello-kiamol